src/common/Chart.yaml
src/common/templates/_databaseconnections.tpl
src/common/templates/_databasehelpers.tpl

1. Added arguments to specify custom env variable names for username and password because different services expect different names.
2. Added custom code for redis connection string and env variables

SMP-1338: add functions for external redis env and connection string

---

src/common/Chart.yaml
src/common/templates/_databaseconnections.tpl

Added database and argument support.
Usage:
If you have local arguments used specifically for a particular microservice it will get appended with global arguments with '&' seperation.
{{ include "harnesscommon.dbconnection.postgresConnection" (dict "database" "harness-sto" "args" "search_path=sto" "context" $) }}
if you have global arguments like:
connect_timeout=10&sslmode=require
it is going to render like this:
- name: APP_DB_MIGRATION_DATASOURCE
value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/harness-sto?search_path=sto&connect_timeout=10&sslmode=require

external Postgres changes to add default database and additional parameters

---

src/common/Chart.yaml
src/common/templates/_capabilties.tpl
src/common/templates/_hpa.tpl

usage: apiVersion: {{ include "harnesscommon.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
{{- if semverCompare "<1.23-0" (include "harnesscommon.capabilities.kubeVersion" .) }} for checking kubernetes version for custom functions

[SMP-1191]: Added capabilites for HPAs for various version switches

---

src/common/Chart.yaml
src/common/templates/_databaseconnections.tpl
src/common/templates/_databasehelpers.tpl
src/common/values.yaml

- We have added external redis authentication support in 800xx but we have 798xx as the release candidate for July.
- We have not gotten required approvals on Hotfix PR for 798xx authentication support yet
- Hence, we will release SMP 0.8.0 without authentication support.
- For that, charts need to support empty secrets.

SMP-1702: add support to use external redis without password

---

src/common/Chart.yaml
src/common/templates/_databaseconnectionsv2.tpl
src/common/templates/_smtp-secrets-helper.tpl
src/common/values.yaml

1. Added tmpl func to support external secrets for SMTP
2. Fixed precedence order of "protocol" field of timescaledb 
Testing:

SMP-2100: Add tmpl function for smtp secrets

---

src/common/Chart.yaml
src/common/templates/_databaseconnectionsv2.tpl
src/common/templates/_eso-secrets-helper.tpl
src/common/templates/_secrets-helper.tpl

1. Add `harnesscommon.dbconnectionv2.isRedisPasswordSet`
2. Update `harnesscommon.dbconnectionv2.mongoEnv ` to support `userVariableName`, `passwordVariableName` as inputs
3. Update `harnesscommon.dbconnectionv2.mongoConnection` to support `userVariableName`, `passwordVariableName` as inputs
4. Add `harnesscommon.secrets.hasSingleValidESOSecret` 
5. Add `harnesscommon.secrets.isDefaultAppSecret`
6. Fix context argument in `harnesscommon.secrets.manageAppEnv` in call to `harnesscommon.secrets.manageEnv`

SMP-2100: Update tmpl functions for External Secrets

---

src/common/Chart.yaml
src/common/templates/_secrets.tpl

Currently helm upgrade can fail due to this bug where if there is an existing secret S, it had a,b,c,d secret keys inside it.
If during an upgrade another key e is added, it will fail with an error: key not present.
This PR will fix the issue to create the secret with already existing logic(generate key if not specified, use secret key if specified).
tested on helm upgrade:
Before ( AZURE_APP_CLIENT_SECRET missing)
After Upgrading(Creates secrets, also other secrets are not impacted):
After Upgrading twice(just in case):

fix: [SMP-2377]: Create a secret key inside an existing secret if doesnt exist

---

src/common/Chart.yaml
src/common/templates/_initContainer.tpl

1. Changed name from `common.initContainer.waitForContainer` to `harnesscommon.initContainer.waitForContainer`
2. Updated chart version (was missed in the previous PR)

Fix: [SMP-2375]: changed function name for waitContainers

---

src/common/Chart.yaml

Bumping up the chart version which was missed in the previous PR

fix: [SMP-2324]: Bump up chart version for podmonitor changes

---

src/common/Chart.yaml
src/common/templates/_dbv3.tpl
src/common/templates/_eso-secrets-helper.tpl

Currently we have to make changes at 4 places, secret.yaml, helpers.tpl, deployment.yaml and values.yaml to just add a secret to a manifest. This makes it hard to add secrets at runtime just using overrides. We should range over the secrets smartly and render
The new file structure of .Secrets should look like:
```
secrets:
fileSecret:
- volumeMountPath: "abc"
keys:
- TEST_VM_ONE
- TEST_VM_SEVEN
- volumeMountPath: "def"
keys:
- TEST_VM_TWO
- TEST_VM_THREE
- TEST_ESO_TWO
- TEST_VM_FIVE
- TEST_VM_FOUR
- TEST_VM_SIX
default:
TEST_VM_ONE: "123"
TEST_VM_TWO: ""
TEST_VM_THREE: ""
TEST_KUBEREXT_TWO: ""
TEST_VM_SEVEN: ""
kubernetesSecrets:
- secretName: "xyz"
keys:
TEST_VM_ONE: ""
- secretName: "def"
keys:
TEST_VM_TWO: "def"
TEST_VM_FIVE: "xyz"
- secretName: "lmo"
keys:
TEST_KUBEREXT_TWO: "lmo" …
```

Add helper functions to generate all secrets just using values.yaml

---

src/common/Chart.yaml
src/common/templates/_eso-secrets-helper.tpl

before: We didnt have a way to set filePath/ fileName to mounted variable( it was set to the variable name itself)
Added a functionality to have ability to name filenames to variables as well:
the syntax for values.yaml has changed a bit to add list of dictionary instead of list. keeping path empty “” , will lead to path being the variablename(previous  behaviour)
```
keys:
- key: TEST_VM_ONE
path: "/abc/deflmo.yaml"
```
Here is the values.yaml
```
secrets:
fileSecret:
- volumeMountPath: "abc"
keys:
- key: TEST_VM_ONE
path: "/abc/deflmo.yaml"
- key: TEST_VM_SEVEN
path: "/test/foobar.txt"
- volumeMountPath: "def"
keys:
- key: TEST_VM_TWO
path: "/abc/def"
- key: TEST_VM_THREE
path: "/test/foo"
- key: TEST_ESO_TWO
path: "/test/bar"
- key: TEST_VM_FIVE
path: "/test/some/other"
- key: …
```

Add setting path functionality

---

src/common/Chart.yaml
src/common/templates/_ingress.tpl

Motivation for change:
- we did not have the capability to remove host from ingress rules. It caused issues if it is deployed alongside nonhost ingress rules
Change the ingress rule to be a one-liner:
```
{{- include "harnesscommon.v1.renderIngress" (dict "ctx" $) }}
```
added fields:
```
global:
ingress:
disableHostInIngress: false <-- disables hostname in ingress rules
pathPrefix: "xyz".  <-- does not do anything, but your path can reference this.
```
```
ingress:
annotations: 
nginx.ingress.kubernetes.io/rewrite-target: /$2
paths:
- path: /authz(/|$)(.*)
- path: /newpath(/|$)(.*)
- path: '{{ .Values.global.ingress.pathPrefix}}/gateway/api'
pathType: Prefix
backend:
service:
port: 9006
name: youCanProvideJustNameLikeThis
```
For SMP:
we need to take care of the following:
- move the …

feat: [PL-48522]: Support a helm template function for ingress rule

---

src/common/Chart.yaml
src/common/templates/_ingress.tpl

Added ability to configure multiple ingress objects.
```
global:
ingress:
disableHostInIngress: false
pathPrefix: ""
pathType: ""
```
```
ingress:
objects:
- annotations: 
nginx.ingress.kubernetes.io/rewrite-target: /$2
paths:
- path: '{{ .Values.global.ingress.pathPrefix }}/pipeline(/|$)(.*)'
- name: pipeline-service-v1-apis
annotations: 
nginx.ingress.kubernetes.io/rewrite-target: /api/$1
paths:
- path: '{{ .Values.global.ingress.pathPrefix }}/(v1/orgs/.+/projects/.+/pipelines.*)'
- path: '{{ .Values.global.ingress.pathPrefix }}/(v1/orgs/.+/projects/.+/input-sets.*)'
- path: '{{ .Values.global.ingress.pathPrefix }}/(v1/pipeline-schema.*)'
- path: '{{ .Values.global.ingress.pathPrefix }}/(v1/orgs/.+/projects/.+/pipelines/.+/execute/stages-execution-list)'
- path: '{{ …
```

Add ability to configure multiple ingress objects

---

src/common/Chart.yaml
src/common/templates/_eso-secrets-helper.tpl

Current behaviour: if the secret contained a hyphen, the externalsecret does translate the secret into the k8s object.
This PR fixes it. 
More details here: https://github.com/external-secrets/external-secrets/issues/1053
its a golang template limitation

Fix secret ref if the secret contains hyphens

---

src/common/Chart.yaml
src/common/templates/_databaseconnectionsv2.tpl
src/common/templates/_dbv3.tpl

Existing timescale functions v2 and v3 will now set protocol based on the argument first then from the values. This will avoid breaking changes to helm charts that have not been updated and maybe relying on default values.
Charts moving forward should update to v4 which will only read it from the arugment.

Fixing timescale templates to use argument first for protocol.

---

src/common/templates/_databaseconnectionsv2.tpl

postgresConnection now sets the sslMode based on the "localDbctx" when enabled. This update only affects sslMode in keyword connection mode. No breaking interface change.

Fixing local sslMode for postgres.

---

src/common/Chart.yaml
src/common/templates/_pdb.tpl

Pod Disruption Budgets are not configurable and for most of the services are set at `minAvailable: 50%`, customers require an option to configure PDBs for all services and the ability to turn them off or on.
This PR adds a helm function that will be used by all services to render the PDB manifest and is configurable through the override file.
The configuration is divided into two parts
- Global: Global configurations will be applied to all services
- Local: These have precedence over global config and can be used to specifically set values for the PDB of a service.

feat: [PL-56708]: adding PDB function

---

src/common/Chart.yaml
src/common/templates/_pdb.tpl

Add fix to pdb helper for charts using different names
Issue found in nextgen-ce chart using ce-nextgen name. Its a corner case here.

feat: [PL-56709]: Add fix to pdb helper for charts using different names

---

src/common/Chart.yaml
src/common/templates/_ingress.tpl

The ingress template function should allow us to define multiple ingress objects. This allows applications to conditionally render different ingress objects for different needs.
This change is fully backward compatible.
Example,
`values.yaml`
```yaml
ingress:
objects:
- annotations:
nginx.ingress.kubernetes.io/rewrite-target: /$2
paths:
- path: '{{ .Values.global.ingress.pathPrefix}}/cdc(/|$)(.*)'
pms:
ingress:
name: change-data-capture-pms
objects:
- annotations:
nginx.ingress.kubernetes.io/rewrite-target: /$2
paths:
- path: '{{ .Values.global.ingress.pathPrefix}}/cdc(/|$)(/sync/pipelines.*)'
enabled: splitDeployment.enabled
backend:
service:
name: change-data-capture-pms
```
`ingress.yaml`
```yaml
{{- include "harnesscommon.v1.renderIngress" (dict "ctx" $) }}
{{- if …
```

fix: [PL-57361]: support multipe ingress definitions

---

src/common/Chart.yaml
src/common/templates/_hpa.tpl

Through this PR we are centralising the HPA configuration. This will add support for the following:
- Add HPA control at both global and service level
- `global.autoscaling.enabled` will have higher precedence over `autoscaling.enabled`
- For `minReplicas` and `maxReplicas`, we won’t have any service-level defaults.
- If service level overrides are set for `minReplicas` and `maxReplicas`, they will have higher precedence over global
- For `targetCPU` and `targetMemory`, service level overrides will have higher precedence over global, same as min/max repliacs.
This way, anyone can fine-tune service-level overrides for minReplicas, maxReplicas, targetCPU and targetMemory
Through helm-charts global override, these default values will be set for all services
```
global:
autoscaling:
enabled: …
```

feat: [PL-57710]: added function to template HPA

---

src/common/Chart.yaml
src/common/templates/_hpa.tpl

Chart builds were failing due to a change in the existing function which did not handle backward compatibility, I have added the condition to work with existing charts
Reproduced issue 
Fixed with the new changes, chart templating

fix: [PL-57710]: added backward compatibility

---

src/common/Chart.yaml
src/common/templates/_databaseconnectionsv2.tpl
src/common/templates/_dbv3.tpl

The database name can be controlled from overrides by adding below:
```
timescaledb:
database: "harness_free"
secondaryTimescaledb:
database: "harness_free"
```
We didnt update the helper argument to avoid breaking existing charts.
@arya-harness to review.

feat: [OPS-31399]: Added capability for database to be overriden

---

src/common/Chart.yaml
src/common/templates/_monitoring.tpl

- Add Support for OSS Prometheus CRD: https://github.com/helm/charts/blob/master/stable/prometheus-operator/crds/crd-podmonitor.yaml, Example: https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/podmonitor.yaml
- Add Support for All fields to be dynamically generated with backward compatibility.
- Add ability to change name of podMonitoring. cc: @manishjaiswal2 
**Test cases:**
**tested with following override**
```monitoring:
port: 8889
path: /metrics
additionalPodMonitorSpec:
sampleLimit: 20
additionalPodMetricsEndpoints:
- port: "9000"
interval: 2000s
path: "/metrics"
PodMetricsEndpointsConfig:
honorLabels: "xyz"
```
**Renders**
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
name: harness-manager-iterator
namespace: default
spec:
selector: …
```

feat: [PL-58202]: Add support for OSS managed Prometheus instance, misc fixes

---

src/common/Chart.yaml
src/common/templates/_images.tpl

Flow - 
1. If only one of digest or tag is present, use it
2. If none are present, throw an error
3. If both are present, use the flag `preferDigest` to decide which to use. Default for `preferDigest` is false.
Also check if the digest format is correct - 
```
gokulbansal@Gokul Bansal chart % helm template . > output.yaml
Error: execution error at (ng-manager/templates/deployment.yaml:63:18): Error: Digest must start with 'sha256:', got 'sha26:52a3a0578d956aa2283c3adf6bcaf86edeeb68be74b6ea4d4236df683547d37a'
Use --debug flag to render out invalid YAML
```
Test cases -    
1. Both image and tog not present
2. Only image tag present
```
image:
registry: us.gcr.io/platform-205701
repository: ng-manager
pullPolicy: IfNotPresent
tag: "1.19.2"
digest: ""
imagePullSecrets: []
```
```
containers: …
```

fix: [PL-60135]: helm common image function to support Digest and Tag

---

src/common/Chart.yaml
src/common/templates/_databaseconnectionsv2.tpl
src/common/templates/_monitoring.tpl

Add ability to set opentelemetry variables under the conditions of monitoring.otel.enabled or global.monitoring.otel.enabled
```
global:
monitoring:
enabled: true
managedPlatform: google
otel:
enabled: true
collectorEndpoint: "https://abcd:4317/"
monitoring:
otel:
enabled: true
collectorEndpoint: "https://defg:4317/"
```

Add ability to support otel in all charts with monitoring enabled, fix pg port function

---

src/common/templates/_images.tpl

[ERROR] [deployNamespace.sh] Helm deployment for harness failed
Error: UPGRADE FAILED: execution error at (harness/charts/platform/charts/bootstrap/charts/database/charts/timescaledb/templates/cronjob-archivecleanup.yaml:34:22): Error: Digest must start with 'sha256:', got '\<nil\>'
Getting this error when image.digest key is not present.
Tested with templating the helm package with changes and didn't get the error again.

Update prefer digest image function to solve nil error
